//! #700 — sway · Hyprland 자동실행을 `tildaz --desktop add | remove` 에서 다룬다.
//!
//! 순정 sway 와 uwsm 없는 Hyprland 는 XDG autostart 를 읽지 않아서, 자동실행은 그 데스크톱의
//! 설정에 있어야 한다. 예전 `install.sh` 는 사용자 설정에 표식과 명령 두 줄을 넣고, 다음
//! 설치 때 "표식 다음 줄" 을 바꿔 썼다. 이제는 이렇게 한다.
//!
//!   - 명령은 **우리 파일**에 둔다 — sway `<설정>/sway/<id>.conf`, Hyprland `<설정>/hypr/<id>.lua`
//!     (Lua) · `<id>.conf` (legacy). 이 파일은 우리 것이라 통째로 다시 쓴다.
//!   - 사용자 설정에는 **불러오는 줄 하나와 그 표식**만 넣는다 (`sway_hyprland_files.zig`).
//!     이미 있으면 쓰지 않는다. 다른 줄은 고치지 않는다.
//!   - 예전 `install.sh` 의 블록은 옮긴다 — 표식 다음 줄이 그 스크립트가 쓴 모양일 때만 지운다.
//!
//! 불러오는 방법과 순서는 upstream 소스로 정했다 (#700 조사 — sway 1.12 · Hyprland v0.56.2).
//!   - sway `include` 는 없는 파일을 조용히 넘기고, 같은 파일은 한 번만 읽는다 (`config.c`
//!     `load_include_config`). `exec` 는 reload 때 다시 돌지 않는다 (`commands/exec.c`).
//!   - Hyprland 은 `hyprland.lua` 가 있으면 `.conf` 보다 먼저 읽는다 (`Jeremy.cpp`). Lua 는
//!     `pcall(require, "<id>")` 가 설정 폴더의 `<id>.lua` 를 읽고, 없으면 오류 없이 넘긴다
//!     (`lua/ConfigManager.cpp` `safeLuaRequire` · `package.path`). legacy `source =` 는 파일이
//!     없으면 **오류 배너**가 뜬다 — 그래서 add 는 우리 파일을 먼저 쓰고, remove 는 불러오는
//!     줄을 먼저 지운다.
//!   - "자동 생성 설정" 배너는 설정을 다 읽은 뒤의 **최종값**으로 정한다 (`postConfigReload`).
//!     그래서 우리 파일이 `autogenerated` 를 끈다 — 예전 `install.sh` 는 사용자 파일의 그 줄을
//!     `sed` 로 지웠는데, 여러 줄로 쓴 `hl.config` 면 Lua 문법이 깨졌다 (#700 D4). 우리 파일을
//!     지우면 배너도 원래대로 돌아온다. 그 배너가 화면 위쪽, 드롭다운이 열리는 자리를 가린다.
const std = @import("std");
const Runtime = @import("../runtime.zig").Runtime;
const app_id = @import("../app_id.zig");
const paths = @import("../paths.zig");
const log = @import("../log.zig");
const console = @import("../console.zig");
const messages = @import("../messages.zig");
const sway_hyprland_files = @import("sway_hyprland_files.zig");
const shortcut_sync_linux = @import("../shortcut_sync/linux.zig");

pub const Mode = enum { add, remove };

const marker_text = app_id.display_name ++ " autostart (added by \"tildaz --desktop add\", removed by \"tildaz --desktop remove\")";
const hash_marker = "# " ++ marker_text;
const lua_marker = "-- " ++ marker_text;
/// 예전 `install.sh` 의 표식 — 그 스크립트와 글자 단위로 같아야 옮길 수 있다.
const old_hash_marker = "# " ++ app_id.name ++ " autostart (added by install.sh — uninstall.sh removes this)";
const old_lua_marker = "-- " ++ app_id.name ++ " autostart (added by install.sh — uninstall.sh removes this)";
const file_header = "Written by \"tildaz --desktop add\". \"tildaz --desktop remove\" deletes this file.";

const Ctx = struct {
    rt: Runtime,
    allocator: std.mem.Allocator,
    mode: Mode,
    exe: []const u8,
    config_home: []const u8,
    home: []const u8,

    fn join(self: Ctx, parts: []const []const u8) ![]u8 {
        return std.Io.Dir.path.join(self.allocator, parts);
    }

    fn say(self: Ctx, text: []const u8) void {
        console.outLine(self.rt.io, text);
    }

    fn sayPath(self: Ctx, comptime fmt: []const u8, path: []const u8) void {
        var buf: [std.Io.Dir.max_path_bytes + 32]u8 = undefined;
        self.say(std.fmt.bufPrint(&buf, fmt, .{path}) catch path);
    }

    /// 없으면 `null`.
    fn read(self: Ctx, path: []const u8) !?[]u8 {
        const file = std.Io.Dir.openFileAbsolute(self.rt.io, path, .{}) catch |err| switch (err) {
            error.FileNotFound => return null,
            else => return err,
        };
        defer file.close(self.rt.io);
        var reader = file.reader(self.rt.io, &.{});
        return try reader.interface.allocRemaining(self.allocator, .limited(4 * 1024 * 1024));
    }

    fn write(self: Ctx, path: []const u8, content: []const u8, existed: bool) !void {
        if (std.Io.Dir.path.dirname(path)) |dir| try paths.ensureDir(self.rt, dir);
        if (!try paths.writeFileIfChanged(self.rt, self.allocator, path, content)) return;
        log.appendLine("desktop", "{s} {s}", .{ if (existed) "updated" else "created", path });
        if (existed) self.sayPath(messages.desktop_updated_format, path) else self.sayPath(messages.desktop_created_format, path);
    }

    fn delete(self: Ctx, path: []const u8) !void {
        std.Io.Dir.deleteFileAbsolute(self.rt.io, path) catch |err| switch (err) {
            error.FileNotFound => return,
            else => return err,
        };
        log.appendLine("desktop", "removed {s}", .{path});
        self.sayPath(messages.desktop_removed_format, path);
    }

    fn exists(self: Ctx, path: []const u8) bool {
        std.Io.Dir.accessAbsolute(self.rt.io, path, .{}) catch return false;
        return true;
    }

    /// `PATH` 에 그 이름의 실행 파일이 있는가 — 그 데스크톱이 깔려 있는지 본다.
    fn installed(self: Ctx, name: []const u8) bool {
        const path_env = self.rt.environ.getPosix("PATH") orelse return false;
        var it = std.mem.tokenizeScalar(u8, path_env, ':');
        var buf: [std.Io.Dir.max_path_bytes]u8 = undefined;
        while (it.next()) |dir| {
            if (!std.Io.Dir.path.isAbsolute(dir)) continue;
            const candidate = std.fmt.bufPrint(&buf, "{s}/{s}", .{ dir, name }) catch continue;
            std.Io.Dir.accessAbsolute(self.rt.io, candidate, .{ .execute = true }) catch continue;
            return true;
        }
        return false;
    }
};

pub fn run(rt: Runtime, allocator: std.mem.Allocator, mode: Mode) !void {
    var exe_buf: [std.Io.Dir.max_path_bytes]u8 = undefined;
    const exe_len = try std.process.executablePath(rt.io, &exe_buf);
    const config_home = try paths.configHome(rt, allocator);
    defer allocator.free(config_home);
    const home = try rt.envAlloc(allocator, "HOME");
    defer allocator.free(home);
    const ctx: Ctx = .{
        .rt = rt,
        .allocator = allocator,
        .mode = mode,
        .exe = exe_buf[0..exe_len],
        .config_home = config_home,
        .home = home,
    };
    try sway(ctx);
    try hyprland(ctx);
}

/// 사용자 설정 하나를 고친다 — 옛 블록을 옮기고, 불러오는 줄을 넣거나 뺀다. 그 파일을 고치지
/// 않을 때 `include_line` 은 `null` 이다 (옛 블록만 옮긴다).
fn editUserConfig(ctx: Ctx, path: []const u8, base: ?[]const u8, syntax: sway_hyprland_files.Syntax, include_line: ?[]const u8) !void {
    var existed = true;
    const original = (try ctx.read(path)) orelse blk: {
        // 없는 파일은 add 가 새로 만들 때만 쓴다 (`base` 가 그 첫 내용).
        const first = base orelse return;
        existed = false;
        break :blk try ctx.allocator.dupe(u8, first);
    };
    defer ctx.allocator.free(original);
    const old_marker = if (syntax == .lua) old_lua_marker else old_hash_marker;
    const marker = if (syntax == .lua) lua_marker else hash_marker;

    var text: []const u8 = original;
    var owned: ?[]u8 = null;
    defer if (owned) |o| ctx.allocator.free(o);
    if (try sway_hyprland_files.withoutLegacyBlocks(ctx.allocator, text, old_marker, syntax)) |migrated| {
        owned = migrated;
        text = migrated;
        log.appendLine("desktop", "migrated the old install.sh autostart block in {s}", .{path});
    }
    if (include_line) |line| {
        const next = switch (ctx.mode) {
            .add => try sway_hyprland_files.withInclude(ctx.allocator, text, marker, line),
            .remove => try sway_hyprland_files.withoutInclude(ctx.allocator, text, marker, line),
        };
        if (next) |n| {
            if (owned) |o| ctx.allocator.free(o);
            owned = n;
            text = n;
        }
    }
    if (existed and std.mem.eql(u8, text, original)) return;
    try ctx.write(path, text, existed);
}

fn sway(ctx: Ctx) !void {
    const own = try ctx.join(&.{ ctx.config_home, "sway", app_id.name ++ ".conf" });
    defer ctx.allocator.free(own);
    const include_line = try std.fmt.allocPrint(ctx.allocator, "include {s}", .{own});
    defer ctx.allocator.free(include_line);

    // sway 가 찾는 순서 (`config.c` `get_config_path`) 의 sway 전용 두 자리. i3 설정은 i3 도
    // 읽으므로 고치지 않는다 — i3 는 X11 이라 TildaZ 가 뜨지 못한다.
    const dot_sway = try ctx.join(&.{ ctx.home, ".sway", "config" });
    defer ctx.allocator.free(dot_sway);
    const xdg_sway = try ctx.join(&.{ ctx.config_home, "sway", "config" });
    defer ctx.allocator.free(xdg_sway);
    const candidates = [_][]const u8{ dot_sway, xdg_sway };

    if (ctx.mode == .remove) {
        for (candidates) |path| try editUserConfig(ctx, path, null, .hash, include_line);
        try ctx.delete(own);
        return;
    }

    var target: ?[]const u8 = null;
    var base: ?[]const u8 = null;
    for (candidates) |path| if (ctx.exists(path)) {
        target = path;
        break;
    };
    if (target == null) {
        const dot_i3 = try ctx.join(&.{ ctx.home, ".i3", "config" });
        defer ctx.allocator.free(dot_i3);
        const xdg_i3 = try ctx.join(&.{ ctx.config_home, "i3", "config" });
        defer ctx.allocator.free(xdg_i3);
        const i3_config = if (ctx.exists(dot_i3)) dot_i3 else if (ctx.exists(xdg_i3)) xdg_i3 else null;
        if (i3_config) |i3_path| {
            try writeSwayOwn(ctx, own);
            var buf: [2 * std.Io.Dir.max_path_bytes + 160]u8 = undefined;
            ctx.say(std.fmt.bufPrint(&buf, messages.desktop_sway_i3_config_format, .{ i3_path, own }) catch messages.desktop_sway_not_installed_msg);
            return;
        }
        if (!ctx.installed("sway")) {
            ctx.say(messages.desktop_sway_not_installed_msg);
            return;
        }
        // 사용자 설정이 생기면 sway 는 시스템 설정을 읽지 않는다. 그래서 새로 만들 때는 시스템
        // 설정을 먼저 불러온다 — 빠지면 기본 단축키가 하나도 없는 세션이 된다.
        target = xdg_sway;
        base = "include /etc/sway/config\n";
    }
    try writeSwayOwn(ctx, own);
    for (candidates) |path| {
        const line: ?[]const u8 = if (std.mem.eql(u8, path, target.?)) include_line else null;
        try editUserConfig(ctx, path, if (line != null) base else null, .hash, line);
    }
}

fn writeSwayOwn(ctx: Ctx, own: []const u8) !void {
    const content = try std.fmt.allocPrint(ctx.allocator, "# {s}\nexec {s} --autostart\n", .{ file_header, ctx.exe });
    defer ctx.allocator.free(content);
    try ctx.write(own, content, ctx.exists(own));
}

fn hyprland(ctx: Ctx) !void {
    const dir = try ctx.join(&.{ ctx.config_home, "hypr" });
    defer ctx.allocator.free(dir);
    const main_lua = try ctx.join(&.{ dir, "hyprland.lua" });
    defer ctx.allocator.free(main_lua);
    const main_conf = try ctx.join(&.{ dir, "hyprland.conf" });
    defer ctx.allocator.free(main_conf);
    const own_lua = try ctx.join(&.{ dir, app_id.name ++ ".lua" });
    defer ctx.allocator.free(own_lua);
    const own_conf = try ctx.join(&.{ dir, app_id.name ++ ".conf" });
    defer ctx.allocator.free(own_conf);
    const lua_include = "pcall(require, \"" ++ app_id.name ++ "\")";
    const conf_include = try std.fmt.allocPrint(ctx.allocator, "source = {s}", .{own_conf});
    defer ctx.allocator.free(conf_include);

    if (ctx.mode == .remove) {
        try editUserConfig(ctx, main_lua, null, .lua, lua_include);
        try editUserConfig(ctx, main_conf, null, .hash, conf_include);
        try ctx.delete(own_lua);
        try removeConfOwn(ctx, main_conf, own_conf);
        return;
    }

    if (!ctx.exists(main_lua) and !ctx.exists(main_conf)) {
        if (systemHyprlandConfig(ctx)) {
            ctx.say(messages.desktop_hyprland_system_config_msg);
            return;
        }
        if (!ctx.installed("Hyprland")) {
            ctx.say(messages.desktop_hyprland_not_installed_msg);
            return;
        }
        // 설정이 없으면 Hyprland 이 기본 `hyprland.lua` 를 만든다 (0.56 `initConfigManager` →
        // `generateDefaultConfig`). 세션은 띄우지 않는다. 예전 `install.sh` 와 같은 방법이다.
        verifyConfig(ctx);
        if (!ctx.exists(main_lua) and !ctx.exists(main_conf)) {
            log.appendLine("desktop", "Hyprland --verify-config did not create a config", .{});
            ctx.say(messages.desktop_hyprland_not_installed_msg);
            return;
        }
    }

    // `.lua` 가 있으면 Hyprland 이 그것을 읽는다. 읽지 않는 쪽은 옛 블록만 옮긴다.
    if (ctx.exists(main_lua)) {
        try writeHyprlandOwn(ctx, own_lua, .lua);
        try editUserConfig(ctx, main_lua, null, .lua, lua_include);
        try editUserConfig(ctx, main_conf, null, .hash, null);
    } else {
        try writeHyprlandOwn(ctx, own_conf, .hash);
        try editUserConfig(ctx, main_conf, null, .hash, conf_include);
    }
}

/// legacy 의 `source =` 는 파일이 없으면 오류 배너를 띄운다. 불러오는 줄을 사용자가 고쳐서
/// 지우지 못했으면 (`withoutInclude` 가 글자 그대로 같은 줄만 지운다) 우리 파일을 지우지 않고
/// 비운다 — 배너 없이 아무 일도 하지 않는 파일이 된다.
fn removeConfOwn(ctx: Ctx, main_conf: []const u8, own_conf: []const u8) !void {
    if (try ctx.read(main_conf)) |text| {
        defer ctx.allocator.free(text);
        if (std.mem.indexOf(u8, text, own_conf) != null) {
            log.appendLine("desktop", "{s} still sources {s} — emptying it instead of deleting", .{ main_conf, own_conf });
            try ctx.write(own_conf, "# " ++ file_header ++ "\n", true);
            return;
        }
    }
    try ctx.delete(own_conf);
}

fn writeHyprlandOwn(ctx: Ctx, own: []const u8, syntax: sway_hyprland_files.Syntax) !void {
    var out: std.ArrayList(u8) = .empty;
    defer out.deinit(ctx.allocator);
    const command = try std.fmt.allocPrint(ctx.allocator, "{s} --autostart", .{ctx.exe});
    defer ctx.allocator.free(command);
    switch (syntax) {
        .lua => {
            try out.appendSlice(ctx.allocator, "-- " ++ file_header ++ "\n");
            try out.appendSlice(ctx.allocator, "hl.on(\"hyprland.start\", function() hl.exec_cmd(");
            try shortcut_sync_linux.appendLuaString(&out, ctx.allocator, command);
            try out.appendSlice(ctx.allocator, ") end)\n");
            try out.appendSlice(ctx.allocator, "-- The autogenerated-config warning bar covers the top of the screen, where TildaZ opens.\n");
            try out.appendSlice(ctx.allocator, "hl.config({ autogenerated = false })\n");
        },
        .hash => {
            try out.appendSlice(ctx.allocator, "# " ++ file_header ++ "\n");
            try out.appendSlice(ctx.allocator, "exec-once = ");
            try out.appendSlice(ctx.allocator, command);
            try out.appendSlice(ctx.allocator, "\n# The autogenerated-config warning bar covers the top of the screen, where TildaZ opens.\n");
            try out.appendSlice(ctx.allocator, "autogenerated = 0\n");
        },
    }
    try ctx.write(own, out.items, ctx.exists(own));
}

/// Hyprland 은 사용자 폴더에 없으면 `XDG_CONFIG_DIRS` (기본 `/etc/xdg`) 에서 찾는다 (hyprutils
/// `findConfig`). 그 설정은 우리가 고칠 수 없다.
fn systemHyprlandConfig(ctx: Ctx) bool {
    const dirs = ctx.rt.environ.getPosix("XDG_CONFIG_DIRS") orelse "/etc/xdg";
    var it = std.mem.tokenizeScalar(u8, if (dirs.len == 0) "/etc/xdg" else dirs, ':');
    var buf: [std.Io.Dir.max_path_bytes]u8 = undefined;
    while (it.next()) |d| {
        if (!std.Io.Dir.path.isAbsolute(d)) continue;
        for ([_][]const u8{ "lua", "conf" }) |ext| {
            const p = std.fmt.bufPrint(&buf, "{s}/hypr/hyprland.{s}", .{ d, ext }) catch continue;
            if (ctx.exists(p)) return true;
        }
    }
    return false;
}

fn verifyConfig(ctx: Ctx) void {
    const result = std.process.run(ctx.allocator, ctx.rt.io, .{
        .argv = &.{ "Hyprland", "--verify-config" },
        .stdout_limit = .limited(1024 * 1024),
        .stderr_limit = .limited(1024 * 1024),
    }) catch |err| {
        log.appendLine("desktop", "Hyprland --verify-config failed: {s}", .{@errorName(err)});
        return;
    };
    ctx.allocator.free(result.stdout);
    ctx.allocator.free(result.stderr);
}
